export default {
  "login": "KAUSTUBHDUBEY790",
  "id": 78341839,
  "node_id": "MDQ6VXNlcjc4MzQxODM5",
  "avatar_url": "https://avatars.githubusercontent.com/u/78341839?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/KAUSTUBHDUBEY790",
  "html_url": "https://github.com/KAUSTUBHDUBEY790",
  "followers_url": "https://api.github.com/users/KAUSTUBHDUBEY790/followers",
  "following_url": "https://api.github.com/users/KAUSTUBHDUBEY790/following{/other_user}",
  "gists_url": "https://api.github.com/users/KAUSTUBHDUBEY790/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/KAUSTUBHDUBEY790/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/KAUSTUBHDUBEY790/subscriptions",
  "organizations_url": "https://api.github.com/users/KAUSTUBHDUBEY790/orgs",
  "repos_url": "https://api.github.com/users/KAUSTUBHDUBEY790/repos",
  "events_url": "https://api.github.com/users/KAUSTUBHDUBEY790/events{/privacy}",
  "received_events_url": "https://api.github.com/users/KAUSTUBHDUBEY790/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Kaustubh Dubey",
  "company": null,
  "blog": "github.com/KAUSTUBHDUBEY790/",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Just into stuff like learn! build! & develop!",
  "twitter_username": null,
  "public_repos": 47,
  "public_gists": 0,
  "followers": 22,
  "following": 20,
  "created_at": "2021-02-01T07:05:25Z",
  "updated_at": "2023-01-15T13:21:35Z"
};
